name: AI Development Pipeline

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
      task_type:
        description: 'Type of development task'
        required: true
        default: 'feature'
        type: choice
        options:
          - feature
          - bug
          - enhancement

jobs:
  analyze-task:
    if: contains(github.event.issue.labels.*.name, 'ai-development')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Download LLM model
        run: |
          mkdir -p models
          curl -L https://huggingface.co/TheBloke/Llama-2-70B-Chat-GGUF/resolve/main/llama-2-70b-chat.Q4_K_M.gguf \
          -o models/llama-2-70b-chat.gguf
          
      - name: Analyze requirements
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python src/handlers/task_analyzer.py

  generate-code:
    needs: analyze-task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Generate code
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: python src/main.py
        
      - name: Run tests
        run: python -m pytest tests/
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          commit-message: "AI-generated code for issue #${{ github.event.issue.number }}"
          title: "Feature: ${{ github.event.issue.title }}"
          body: |
            Automated PR for issue #${{ github.event.issue.number }}
            
            Generated code includes:
            - Implementation
            - Tests
            - Documentation
            
            Please review the changes.
          branch: feature/issue-${{ github.event.issue.number }}
          base: main
          labels: ai-generated, needs-review

  review-code:
    needs: generate-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Code Review
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: python src/handlers/code_reviewer.py
