name: AI Development Pipeline

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to monitor (owner/repo)'
        required: true
      issue_number:
        description: 'Issue number to process'
        required: true
  repository_dispatch:
    types: [ai-development-task]

jobs:
  analyze-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Analyze requirements
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TARGET_REPO: ${{ github.event.client_payload.repository || github.event.inputs.repository }}
          ISSUE_NUMBER: ${{ github.event.client_payload.issue_number || github.event.inputs.issue_number }}
        run: python src/handlers/task_analyzer.py

  generate-code:
    needs: analyze-task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate code
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TARGET_REPO: ${{ github.event.client_payload.repository || github.event.inputs.repository }}
        run: python src/main.py
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          repository: ${{ github.event.client_payload.repository || github.event.inputs.repository }}
          commit-message: "AI-generated code for issue #${{ github.event.client_payload.issue_number || github.event.inputs.issue_number }}"
          title: "Feature: AI Implementation"
          body: |
            Automated PR for issue #${{ github.event.client_payload.issue_number || github.event.inputs.issue_number }}
            
            Generated code includes:
            - Implementation
            - Tests
            - Documentation
            
            Please review the changes.
          branch: feature/ai-implementation
          base: main
          labels: ai-generated, needs-review