name: AI Development Workflow

on:
  issues:
    types: [labeled]

jobs:
  debug:
    if: contains(github.event.issue.labels.*.name, 'ai-development')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Debug Information
      run: |
        pwd
        ls -la
        python --version