name: AI Development Workflow

on:
  issues:
    types: [opened, labeled]

jobs:
  debug-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Debug Information
      run: |
        echo "Workflow triggered by event: ${{ github.event_name }}"
        echo "Issue labels: ${{ toJson(github.event.issue.labels) }}"
        echo "Repository: ${{ github.repository }}"
    
    - name: Check for AI Development Label
      if: "!contains(github.event.issue.labels.*.name, 'ai-development')"
      run: |
        echo "No 'ai-development' label found. Skipping workflow."
        exit 0
    
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install groq
    
    - name: System and Environment Check
      run: |
        pwd
        ls -la
        python --version
        pip list
    
    - name: Run AI Development Orchestrator
      env:
        GROQ_API_KEY: ${{ secrets.GROQ }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        python src/main.py || echo "Script execution failed"
    
    - name: Prepare Generated Code
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git checkout -b ai-generated-$(date +"%Y%m%d-%H%M%S")
        git add .
        git commit -m "AI Generated Code" || echo "No changes to commit"
        git push origin HEAD
